# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
# write your code here ^_^
# craete 15 elements from 1 to 50
array = np.linspace(1, 50, 15 , dtype=float)
array

array([ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. , 25.5, 29. , 32.5, 36. ,
       39.5, 43. , 46.5, 50. ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [9]:
# write your code here ^_^
# create the arrays
arr1 = [1.1,2.1,3.1]
arr2 = [4.1,5.1,6.1]
arr3 = [7.1,8.1,9.1]
arr4 = [10.1,11.1,12.1]
arr_3d = np.array([[arr1,arr2], [arr3,arr4]])
arr_3d

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [15]:
# write your code here ^_^
def array_info(arr):
    return f"array's type: {type(arr)}, array's elements datatype: {arr.dtype}, array's shape{arr.shape}, array's size:{arr.size}, array's dimention: {arr.ndim}"


array_info(arr_3d)

"array's type: <class 'numpy.ndarray'>, array's elements datatype: float64, array's shape(2, 2, 3), array's size:12, array's dimention: 3"

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [21]:
# write your code here ^_^
new_array = arr_3d.reshape(1,2,2,3)
f"array's dimention: {new_array.ndim}, array's shape: {new_array.shape}"

"array's dimention: 4, array's shape: (1, 2, 2, 3)"

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [23]:
# write your code here ^_^
array_int = new_array.astype('int')
array_int

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [27]:
# write your code here ^_^

for i in np.nditer(array_int):
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [48]:
# write your code here ^_^
array_int[0,1,0,1]


8

In [49]:
array_int

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [51]:
# write your code here ^_^

print(f'nunber 5: {array_int[0,0,1,1]}')
print(f'number 6: {array_int[0,0,1,2]}')

nunber 5: 5
number 6: 6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [53]:
# write your code here ^_^
eight = np.where(array_int == 8)
eight

(array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [62]:
# write your code here ^_^
arr_reshape = array_int.reshape(2,3,2)
arr_reshape

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [59]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
arr3 = np.concatenate((arr1,arr2))
arr3

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [60]:
# write your code here ^_^
arr4 = np.concatenate((arr1,arr2) , axis=1)
arr4

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [68]:
# write your code here ^_^
a,b = np.array_split(arr3,2, axis=1)
print(f'array 1: {a}')
print(f'array 2: {b}')


array 1: [['A']
 ['E']
 ['C']
 ['G']]
array 2: [['B']
 ['F']
 ['D']
 ['H']]
