In [4]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [5]:
# write your code here ^_^
#create array with 3 elements = 1
x = np.ones(3)
print(x)


[1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [6]:
# write your code here ^_^
#create array with 3 elements = 0
y  = np.zeros(3)
print(y)

[0. 0. 0.]


## Q#3: Add x and y arrays.

In [7]:
# write your code here ^_^
# add x y using numpy add fuction
addxy = np.add(x,y)
print(addxy)

[1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [8]:
# write your code here ^_^

#get arry x dimension
x.ndim

1

In [9]:
#get get arry x shape
x.shape

(3,)

In [10]:
#get array x size
x.size

3

In [11]:
#get array x type
type(x)

numpy.ndarray

In [12]:
# get array x elemenet type
x.dtype

dtype('float64')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [13]:
# write your code here ^_^
#creatw 2D array
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [32]:
# write your code here ^_^
#create array from 1,3
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [89]:
# write your code here ^_^
#newArray = np.concatenate(z,w)
#newArray
z_reshape = z.reshape(-1,1)
newArray = np.hstack((w,z_reshape))
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [65]:
# write your code here ^_^
for i in np.nditer(newArray):
    print(i)


11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [66]:
# write your code here ^_^
newArray.T

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [90]:
# write your code here ^_^

newArray = np.subtract(newArray,1)
newArray

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [71]:
# write your code here ^_^
print(f'smallest values in array = {newArray.min()}' )


smallest values in array = 0


In [72]:
print(f'biggest values in array = {newArray.max()}' )


biggest values in array = 15


## Q#12: Print the first row of "newArray" using indexing.

In [73]:
# write your code here ^_^
newArray[:1]

array([[10, 11,  0]])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [83]:
# write your code here ^_^
newArray[1:2,:1]


array([[12]])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [85]:
# write your code here ^_^
#printing number 0
newArray[:1, 2:]

array([[0]])

In [86]:
#printing number 13
newArray[1:2, 1:2]

array([[13]])

## Q#15: Change the shape of "newArray" to (9,1).

In [91]:
# write your code here ^_^
arr = newArray.reshape(9,1)

## Q#16: Change the shape of "newArray" to (3,2).

In [95]:
# write your code here ^_^
#cannoy reahape array of 9 elements into (3,2)
newArray.reshape(3,3)

array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

# Well Done 🎉